# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Rchamp_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install linux packages
        run: |
        sudo apt-get install libcurl4-openssl-dev
      
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Setup dependencies
        run: |
          R -e 'install.packages("renv")' 
          R -e 'renv::restore()'
          
      - name: Run First function
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          R -e 'renv::run("R/first_function.R")'
          
